# Generated by Django 4.1.3 on 2022-11-12 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("list_task", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="datecompleted",
            field=models.DateField(blank=True, null=True),
        )
    ]
